package com.zhongjiang.kotlin.base.common

/**
 * Created by dyn on 2018/7/25.
 */
interface YouXuanFieldConstant {
    companion object {
            val API_DATA_FIELD_ARTICLEID = "articleId"
            val API_DATA_FIELD_OSTYPE = "osType"
            val API_DATA_FIELD_SHARETYPE = "shareType"
            val API_DATA_FIELD_COMMENTS = "comments"
            val API_DATA_FIELD_SUBTITLE = "subtitle"
            val API_DATA_FIELD_TITLE = "title"
            val API_DATA_FIELD_CONTENT = "content"
            val API_DATA_FIELD_HOMEPICTURE = "homePicture"
            val API_DATA_FIELD_KEYWORDS = "keywords"
            val API_DATA_FIELD_SHOPID = "shopId"
            val API_DATA_FIELD_SHOPTYPE = "shopType"
            val API_DATA_FIELD_SHOPADDRESS = "shopAddress"
            val API_DATA_FIELD_SHOPCITY = "shopCity"
            val API_DATA_FIELD_SHOPIMG = "shopImg"
            val API_DATA_FIELD_SHOPNAME = "shopName"
            val API_DATA_FIELD_SHOPPHONE = "shopPhone"
            val API_DATA_FIELD_SHOPSCORE = "shopScore"
            val API_DATA_FIELD_COMMENTID = "commentId"

            const val API_DATA_FIELD_PAGE = "page"
            val API_DATA_FIELD_ID = "id"
            const val API_DATA_FIELD_PAGESIZE = "pageSize"
            val API_DATA_FIELD_TOTALPAGE = "totalPage"
            val API_DATA_FIELD_PAGE_INFO = "pageInfo"
            val API_DATA_FIELD_DATALIST = "dataList"
            val API_DATA_FIELD_DATA = "data"
            val API_DATA_FIELD_ARTICLESTATUS = "articleStatus"
            val API_DATA_FIELD_LAT = "lat"
            val API_DATA_FIELD_LNG = "lng"
            val API_DATA_FIELD_AREACODE = "areaCode"
            val API_DATA_FIELD_USERNAME = "userName"
            val API_DATA_FIELD_CITYCODE = "cityCode"
            val API_DATA_FIELD_CITYNAME = "cityName"
            val API_DATA_FIELD_ISOPEN = "isOpen"
            val API_DATA_FIELD_ISSIGN = "isSign"
            val API_DATA_FIELD_ADDRESS = "address"
            const val API_DATA_FIELD_APPTYPE = "appType"
            val API_DATA_FIELD_MSGCONTENT = "msgContent"
            val API_DATA_FIELD_MSGTYPE = "msgType"
            val API_DATA_FIELD_SIGN_NUMBER = "signNumber"
            val API_DATA_FIELD_SIGN_SUMNUMBER = "signSumNumber"
            val API_DATA_FIELD_NO_SIGN_SUMNUMBER = "noSignNumber"
            val API_DATA_FIELD_CODE = "code"
            val API_DATA_FIELD_REGCODE = "regCode"
            val API_DATA_FIELD_SHOWMESSAGE = "showMessage"
            val API_DATA_FIELD_STATUS = "status"
            val API_DATA_FIELD_HEADURL = "headUrl"
            val API_DATA_FIELD_ROLENAME = "roleName"
            val API_DATA_FIELD_ROLEREMARK = "roleRemark"
            val API_DATA_FIELD_USERID = "userId"
            val API_DATA_FIELD_INVITECODE = "inviteCode"
            val API_DATA_FIELD_AREANAME = "areaName"
            val API_DATA_FIELD_TICKET = "ticket"
            val API_DATA_FIELD_SIGNATURE = "signature"
            val API_DATA_FIELD_USER_AGENT = "User-Agent"
            val API_DATA_FIELD_SERVERID = "serverId"
            val API_DATA_FIELD_ADDRESSID = "addressId"
            val API_DATA_FIELD_ARTIFICERID = "artificerId"
            val API_DATA_FIELD_COUPONID = "couponId"
            val API_DATA_FIELD_ISPOSSIBLE = "isPossible"
            val API_DATA_FIELD_REMARK = "remark"
            val API_DATA_FIELD_SERVTIME = "servTime"
            val API_DATA_FIELD_SERVTYPE = "servType"
            val API_DATA_FIELD_STANDLISTSTR = "standListStr"
            val API_DATA_FIELD_DESCRIBE = "describe"
            val API_DATA_FIELD_IMAGEURLS = "imgUrls"
            val API_DATA_FIELD_ISQUICKLY = "isQuickly"
            val API_DATA_FIELD_LON = "lon"
            val API_DATA_FIELD_SERVICETIME = "serviceTime"
            val API_DATA_FIELD_SERVICETYPE = "serviceType"
            val API_DATA_FIELD_SERVPROJID = "servprojId"
            val API_DATA_FIELD_SERVPROJNAME = "servprojName"
            val API_DATA_FIELD_TAGIDS = "tagIds"
            val API_DATA_FIELD_TAGNAMES = "tagNames"
            val API_DATA_FIELD_TRADEID = "tradeId"
            val API_DATA_FIELD_TRADENAME = "tradeName"
            val API_DATA_FIELD_VOICEURL = "voiceUrl"
            val API_DATA_FIELD_BESPEAKID = "bespeakId"
            val API_DATA_FIELD_ORDERNUMBER = "orderNumber"
            val API_DATA_FIELD_CHANGETYPE = "changeType"
            val API_DATA_FIELD_ISALL = "isAll"
            val API_DATA_FIELD_STANDNUM = "standNum"
            val API_DATA_FIELD_SERVID = "servId"
            val API_DATA_FIELD_REDPAPERID = "redPaperId"
            val API_DATA_FIELD_SORTTYPE = "sortType"
            val API_DATA_FIELD_GPSX = "gpsX"
            val API_DATA_FIELD_GPSY = "gpsY"
            val API_DATA_FIELD_SEARCHKEY = "searchKey"
            val API_DATA_FIELD_TAGID = "tagId"
            val API_DATA_FIELD_KEY = "key"
            val API_DATA_FIELD_ACTIVITYRAPLIST = "activityRapList"
    }
}